### ISSUE TITLE
[Minneapolis, MN/US] Senior Front-End Developer at Drip

### ISSUE THREAD

**Issue by derrickreimer** [FidelisClayton/elm-jobs#20]
Hello! [Drip](https://www.drip.com) is looking for a front-end engineer to work on a cool new Elm project — a visual email builder. (And between you and me, I’d love to see Elm throughout our app front-end codebase someday). 

This is one of the most central pieces of our product, so the opportunity to deliver joy and impact our 20,000+ user base is high. We are small but mighty engineering team inside of well-funded SaaS company — I’m the technical co-founder of Drip and still get my hands dirty in code. 

If you are passionate about Elm and interested in this fun new challenge, I’d love to chat! http://leadpages.jazz.co/apply/0dPJfoLBZZ/Senior-FrontEnd-Developer-Drip

**Comment by armatures** [comment]
I just moved to Minneapolis! I'll definitely be applying.

**Comment by derrickreimer** [comment]
Cool!

**Comment by andys8** [comment]
Link says
> Hiring for this position has been put on hold at this time.

Close?

**Comment by derrickreimer** [comment]
Thanks for the bump! Happy ending to this story -- we hired @armatures!

**Comment by andys8** [comment]
Wow, great to hear!
