### ISSUE TITLE
[London/UK] Front end developer

### ISSUE THREAD

**Issue by jcinnamond** [FidelisClayton/elm-jobs#4]
Are you interested in learning Elm or React, working with some lovely people, having pretty much unlimited opportunity for career growth, and finding a working environment that suits you?

We’re a B2B startup, our customer base is growing quickly, things are going well, and it’s time to find our second developer.

## Who we are

Hi. We’re Indigo&. We help big companies buy expertise from small companies, and help small companies find new clients.

We’re currently a team of five with only one developer. The current team are experienced, ambitious, pragmatic and balanced. Everyone works very closely and this makes for a fast paced and supportive working environment.

## What we are looking for? 

We want someone to take over the front end development, taking our site from a boring list of text to a rich, interactive experience that’s a delight to use. You’ll help us pick the right technologies to achieve this and shape the direction we go in.

The day to day work will involve all aspects of front end development: from writing code, to working with CSS, to helping choose the tools we use. You’ll be working closely with the rest of the business to help us understand and refine our requirements, and then working with the dev team to turn that into high quality working code. 

We would expect you to already be competent in JavaScript and know how to make websites that look great and work well. We can help you learn any other technologies required. From time to time you would be expected to get involved in some backend work, perhaps some devops, pretty much anything else you might be interested in. We’re a startup so you’ll be involved in all sorts of things. We’ll help you find the things you enjoy and give you the opportunity to do more of them.

## What it’s like to work here

You get all the pros and cons that come with working for a startup. Every member of the company has both an opportunity and an obligation to make a difference. We value honesty and openness and believe that these are essential to maintain the close working relationships we have between everyone in the business. We don’t have all the answers. We don’t expect you to have them either, but we’ll work together to find them.

As a team we are too small and moving too fast to not be supportive. Everybody in the business is accessible and we all talk to each other every day, sometimes a lot... 

We are a distributed team, working from offices in Central London or Cambridge, or from home. We try to get together one day per week, for lunch if nothing else.

Diversity is important to us as a business. Our founder is a member of the Diversity and Inclusion Committee at the Royal Academy of Engineering. We are committed to building a diverse and inclusive company because we believe that it is the best way to achieve success. Read more here: [Indigo&'s Diversity Policy](http://www.indigoand.com/careers/diversity-policy_201705/). 

## Why you might want to join

First up, we’ll pay you for it. We’re offering competitive salaries, 30 holidays (+ bank holidays), a pension and we are working on other bits and pieces. As a startup we are lucky because we have the opportunity to shape the other benefits around what our staff want or need. 

You’ll be joining the company at an early stage so you’ll have a strong influence over everything we do. This ranges from deciding what technologies we use, how we work as a team, how we work as a business, even what kind of company we are.

We offer flexible working.  What does that mean for us? It means that you’ll have the option to work from wherever suits you, at whatever times work well for the team and we welcome applications from those who want to work part time. The most important thing is finding the best candidate and creating an environment where everyone can thrive.

Startup life can be intense at times, but we believe it’s important to create an environment that everybody enjoys working in, and where they feel that their contribution is valued. So if you think you have a contribution to make, and would like to enjoy your work, please send a CV and cover letter to jobs@indigoand.com and we will be in touch.

**Comment by kushalj** [comment]
Just got a reply to my application - these guys have filled the position.

**Comment by jcinnamond** [comment]
Apologies - I forgot to close this when we found someone.
