### ISSUE TITLE
[London/UK] Full Stack Developer

### ISSUE THREAD

**Issue by joecorkerton** [FidelisClayton/elm-jobs#44]
### At Stowga we are building the world’s warehousing marketplace.

Stowga matches warehouses with companies looking to take space on-demand. By creating a marketplace to search, compare and book warehouses we have reduced a process that used to take months to minutes.

This completely changes how companies think about their supply chains. With Stowga clients can build completely dynamic, flexible supply chains and respond in real-time to business needs.

Based in London and backed by top tier investors, we are assembling a world-class team of technology and logistics experts to build a category defining product, one that will change an entire industry globally. The prize is enormous: logistics is one of the very few genuine trillion dollar markets yet to be disrupted by technology.

### The role

Our stack is Rails on the backend and a mix of Elm and JS on the front end. We are finding ourselves using Elm for an increasingly large number of features on the site.

No previous Elm experience required.

The full job listing can be found here https://angel.co/stowga/jobs/291317-full-stack-developer.

If you're interested, send a CV to jobs@stowga.com

**Comment by TechnoTone** [comment]
This job listing has been removed.
