### ISSUE TITLE
[Stockholm, Sweden] Full-Stack Developer (Elm/TypeScript)

### ISSUE THREAD

**Issue by michelr** [FidelisClayton/elm-jobs#50]
We (Insurello) are seeking for a passionate Elm developer. Read the description below and if you would like to apply follow this link [Passionate Full-Stack Developer](https://jobb.insurello.se/jobs/895819-full-stack-developer-interested-in-functional-programming-elm-typescript-f?promotion=81078-trackable-share-link-elm-slack) or write a mail with your CV to me at michel@insurello.se.

### Our story
Every year **6 billion SEK** of personal accident insurance compensation go unclaimed in Sweden!

One of the biggest reasons is that it is complicated to go through the claims process and requires both time, knowledge and a lot of patience.
This ends now!

We are Insurello, and we have developed the first digital solution that helps people claim their accident insurances money instantly online. We have been an instant hit in the market, and now we’re in the process to find new interesting people.

### Who we are - do you want to be a part of our everyday life?

- We are all passionate about continuously improving our product. Helping our customer service team with new features or improving the customer journey is happiness for us!
- We are interested in and want to learn functional programming. Today we use Elm and TypeScript, but we are always open to testing other alternatives if it benefits our product.
- We work together and usually with mob programming or pair programming. We believe in an agile way of working, and we are happy to remove unnecessary meetings, excessive detailing, and time estimates.
- We believe in our architecture - event sourcing with microservices. We make sure our team understands and feels pride and participation in the architecture we have chosen.
- We are curious and want to share what we have learned. We organize meetups and talk informally about code and architecture in our book club.

**Our stack:**
Elm, TypeScript with Node.js, RabbitMQ, PostgreSQL all on AWS with Docker.

### Who you are
- You want to be a part of our product development culture which is experimental and challenging but prioritized to deliver the best value to our growing customer base.
- You've been a developer for a couple of years and are passionate about learning new things. If you have previous experience within functional languages, it's an advantage but certainly not a requirement.
- You think it's fun and rewarding to work in a group and like code reviews and testable code. You thrive in an environment where we solve problems together, and you freely share your knowledge and experiences.
- You find it exciting to work in a fast-paced startup environment where you can be involved in most things and work close to all different areas of expertise.

### Why Insurello?
We are convinced that we have a product that will aid millions of people and change an extremely sluggish industry. At the same time, we know that the key to success is the right people, working together in a functioning team always having fun and getting challenged continuously.

We hope that you want to be a part of our team and help us succeed in our ambitious journey!

**Comment by nikican** [comment]
Hi Michel,

Is this ad still active?

**Comment by michelr** [comment]
@nikican 

> Hi Michel,
> 
> Is this ad still active?

Yes it is, I updated the link now to the job page!
