### ISSUE TITLE
[Las Vegas / NV] FE Developers with ELM On Site

### ISSUE THREAD

**Issue by idonohue** [FidelisClayton/elm-jobs#51]
Looking for folks who are interested / experienced with #elm.
Cutting edge company that is partnering w/ IBM using Watson APIs for SaaS product offerings in the #lasvegas area (Onsite - relo available). Pls DM me if you are interested.
@idonohue

**Comment by alythobani** [comment]
DM isn't possible on GitHub. Any other way to contact?

**Comment by idonohue** [comment]
Can you email me at ivan@hellotalented.com 

Ivan Donohue / Recruiting / Hello, Talented
O: (503) 389-3174 / M: (323) 578-8406 / add/follow me on LI!
