### ISSUE TITLE
[London/Remote] Elm Developer

### ISSUE THREAD

**Issue by danielegalluccio** [FidelisClayton/elm-jobs#52]
### Skills & Requirements

- Strong understanding of Elm
- Proficient understanding of cross-browser compatibility issues and ways to work around such issues
- Proficient understanding of code versioning tools, such as Git
- Knowledge of Ruby and Elixir highly beneficial

### What you will do

- You will help us build a dynamic front-end in Elm
- You will be the champion and go-to person for Elm questions

### What we offer

- in office or remote working
- brilliant people to work with

### What we Expect

- you are (ideally immediately) available
- you living or are willing to work in a reasonable overlap of GMT/BST hours
- you play well with others

Please contact daniele.galluccio@mymedsandme.com if you are interested.
Note that this is (at least for the moment) a freelance engagement (apologies, I seem unable to edit labels for this issue).

**Comment by AntonRich** [comment]
Hi Daniel. You haven't left any contact information.

**Comment by danielegalluccio** [comment]
> Hi Daniel. You haven't left any contact information.

Apologies. corrected.

**Comment by danielegalluccio** [comment]
role fulfilled. thanks to all who applied
