### ISSUE TITLE
[Stuttgart, Berlin, Lisbon / Germany, Portugal] Mercedes-Benz.io looking for elm devs

### ISSUE THREAD

**Issue by janwirth** [FidelisClayton/elm-jobs#55]
:car:  Mercedes-Benz | Berlin + Stuttgart Germany; Lisbon, Portugal

:wave: @filipemoraisjorge, @tiagodeoliveira and I are working on a *project using elm at mercedes-benz.io. We are looking to staff up our team.*

We work with *experts of design, product and marketing*. We are using a mix of lean and design thinking to develop a product on top of tested hypothesis. You could say *we are applying the scientific method to product development.* 👩‍🔬 👨‍🔬 

If this sounds interesting to you send us a direct message. *We are looking forward to build with you!*
https://www.mercedes-benz.io/ is located in Stuttgart, Lisbon and Berlin. *Applications from places nearby welcome* (we are a distributed team anyways).

_Greetings from Berlin_

**Comment by eimfach** [comment]
Hey @FranzSkuffka I am very interested in this job. I am from Berlin :)

**Comment by janwirth** [comment]
@eimfach sent you a mail. Can't promise anything though.

**Comment by dominiq-eu** [comment]
Hey @FranzSkuffka,

I am from Berlin and interested in this job.
Thanks
=)

**Comment by janwirth** [comment]
This job posting is closed unfortunately

**Comment by janwirth** [comment]
Open positions can be found here:
https://www.mercedes-benz.io/jobs/

Elm is not in the stack anymore though :joy:
