### ISSUE TITLE
[London] Senior Elm/Elixir/Ruby/Javascript developer 

### ISSUE THREAD

**Issue by opsb** [FidelisClayton/elm-jobs#57]
You’ll be working across two product, Bean (https://www.usebean.com), and a new open banking project. Bean set out to help people save money and optimise their outgoings through scanning their bank transactions and identifying recurring spend. Our purpose is to ensure people only spend what they needed to spend by cancelling what isn’t needed and switching to cheaper alternatives. Far too many companies use user apathy to charge more. Bean aims to stop that. Ultimately we want to help people improve their finances and take the stress out of it. Post BGL acquisition, we’re looking to massively scale this and fully embrace open banking. 

If you’re interested, please send your CV to jobs@usebean.com.

**What we want:**
Someone who wants to use their skills to help people rather than getting them hooked, spend money, etc
Has a passion for their craft but also a degree of pragmatism. Perfection is subjective and unachievable.
Gets their kicks from users using their work, not white paper implementations.
Not scared of learning new things. Can bring their new learnings to their job and team. 
Is team orientated. We deliver as a team, we fail as a team. No rockstars, ninjas or any other self absorbed titles.
Understands that not everything needs to be solved with a ‘technical hammer’. 
A problem solver, not a code monkey.
Polyglot developers (specialism in either Ruby, Javascript, Elixir or Elm)

**What we do:**
Make design decisions together.
Deliver quality software.
Make incremental improvements.
Practise the agile manifesto.
Resist process for process sake.
Use the right tools for the job.
Share ideas and knowledge.
Continuously learn, improve and grow.
Learn from our success and failures.
Hammock driven development (look it up - excellent talk by Rich Hickey)

**What we don’t do:**
Ivory tower architecture.
Ignore tech debt.
Add more tech debt.
Work around problems.
Deliver the wrong solution.
Use techs because they look good on our CVs.
Take ourselves too seriously.

Tech we currently use:

- Elm
- Elixir
- Ruby on Rails
- Rspec
- AWS
- Terraform
- Postgres
- React
- React Native
- Redux
- Rxjs
- Express
- Git

Generally, if we can justify it, we can use it.

**Next steps:**
Send us your cv (jobs@usebean.com).
15-30 minute chat (telephone, hangout, etc) - general chat, nothing heavy.
Take home test - something related to what we do.
1-2 hour face-to-face interview - we’ll talk about your test, enhancements, and then a general chat about you and us.

**Comment by Janiczek** [comment]
Hey @opsb! :wave: Given the Bean website says
> Bean has now been discontinued.

Is this posting still relevant / same team working on the Meerkat app?
