### ISSUE TITLE
[Kingston/UK] Full-Time Elm Developer at Emirates Group

### ISSUE THREAD

**Issue by jwbrew** [FidelisClayton/elm-jobs#62]
We're looking for 3 Elm developers or Elm-learners to join our team at Emirates to work on an internal booking platform. Currently at 150k lines of code (lots of encoders & decoders!), you'll join the team and help build out the next generation of the product, designed to scale to more than 10x the current volume. 

Drop me a line if you're interested - jbradley@travelrepublic.co.uk. I'm the principal engineer on the project and we'll be working closely together throughout. 

### Skills & Requirements
Experience with Elm 

OR

- A hunger to learn Elm & functional programming
- Existing experience with front-end, FP and/or a type system
- Some JS experience including the Flux architecture (Redux etc)

**Comment by sacabuche** [comment]
Hi @jwbrew are you still looking for devs?

**Comment by jwbrew** [comment]
Hey @sacabuche - not currently I'm afraid but I can drop you a line if anything changes?

**Comment by sacabuche** [comment]
@jwbrew sure! that would be awesome. Thank you
