### ISSUE TITLE
[Eastern Europe] Part-time long-term Elm developer (remote)

### ISSUE THREAD

**Issue by kasparpalgi** [FidelisClayton/elm-jobs#64]
Hey guys! Pls, email me kaspar@crewnew.com if you're Elm dev and want to work with cool startup built in Elm and Node. Thanks.

**Comment by Petka17** [comment]
@crewnew Hi
Is there a job description that you can share here?

**Comment by kasparpalgi** [comment]
Hi Petr,

Thanks for your interest. The elm site you need to work on is bookswap.co.uk
and I'll share the task list and codebase with you shortly. Let me know if
we could have a quick call today maybe with screen sharing and also what's
your hourly rate.

Regards,

Kaspar L. Palgi
Project manager, Strategist, Developer

+44 (0) 203 98 4949 5 (Office)
+44 (0) 75 886 999 48 (WhatsApp)
+372 52 8888 46 (Travel)

*crewnew.com <https://crewnew.com/> / *One-Pager <https://z-9.eu/1pager>

[image: Agency Quality with Freelancer Prices]     [image: WhatsApp]
<https://wa.me/447588699948>   [image: Skype]
<https://join.skype.com/invite/eE157gDqqEcY>   [image: LinkedIn]
<https://www.linkedin.com/company/crewnew>   [image: WhatsApp]
<https://www.facebook.com/crewnewcom>   [image: WhatsApp]
<https://twitter.com/crewnew_com>

**Comment by tomazbracic** [comment]
Is this still active?

**Comment by kasparpalgi** [comment]
Hi everybody! We found already one Elm dev but Elm is great so we're in the need for another Elm dev already:) Please, email to job@crewnew.com about your interest:)
